namespace :wiki do
  desc "Erstellt Wiki-Artikel aus dem CocktailScout-Lexikon (idempotent)"
  task seed_lexicon: :environment do
    author = User.find_by(username: "rrr")
    abort "Benutzer 'rrr' nicht gefunden." unless author

    entries = [
      # --- A ---
      { title: "Abseihen", body: "Das sorgfältige Ausgießen eines Drinks durch ein [[wiki:barsieb|Barsieb]], um Eis und Fruchtstücke zurückzuhalten." },
      { title: "Absinth", body: "Hochprozentiger Spirituose aus Wermut, Anis und Fenchel. Historisch als \"Grüne Fee\" bekannt. Enthält [[wiki:thujon|Thujon]] als charakteristischen Wirkstoff. Wird traditionell mit Wasser und Zucker über einen [[wiki:absinthloffel|Absinthlöffel]] serviert." },
      { title: "Absinthe-Fontaine", body: "Dekorativer Wasserspender mit regelbaren Hähnen für die traditionelle Absinth-Zeremonie. Das Eiswasser tropft langsam über einen [[wiki:absinthloffel|Absinthlöffel]] mit Zuckerwürfel in das Glas." },
      { title: "Absinthlöffel", body: "Spezieller Löffel mit Schlitzen oder Aussparungen für die Absinth-Zeremonie. Der Zuckerwürfel wird auf dem Löffel platziert und durch herabtropfendes Wasser aufgelöst." },
      { title: "AF-Cocktail", body: "Alkoholfreier Cocktail (\"Alkoholfrei\"). Häufig als Nachahmung alkoholischer Cocktails konzipiert und auch als \"Virgin\"-Drink bezeichnet. Siehe auch [[wiki:mocktail|Mocktail]]." },
      { title: "After-Dinner-Cocktail", body: "Cocktail, der nach einer Mahlzeit als [[wiki:digestif|Digestif]] gereicht wird. Meist süßer und gehaltvoller als andere Cocktailkategorien." },
      { title: "Agraffe", body: "Drahtkorb, der den Korken einer Sektflasche sichert. Auch als [[wiki:muselet|Muselet]] (franz.) bezeichnet." },
      { title: "Agrest", body: "Historische Bezeichnung für [[wiki:verjus|Verjus]] – Saft unreifer Weintrauben." },
      { title: "Agricole", body: "Produktionskennzeichnung für Rum, der direkt aus frisch gepresstem Zuckerrohrsaft (statt Melasse) gebrannt wird. Typisch für die französischen Antillen. Siehe auch [[wiki:rhum-agricole|Rhum Agricole]]." },
      { title: "Aguardientes de Orujo", body: "Spanischer Tresterbrand aus Galicien mit geschützter Herkunftsbezeichnung. Vergleichbar mit der italienischen [[wiki:grappa|Grappa]]." },
      { title: "Alambic", body: "Brennhelm bzw. Kupferkessel der traditionellen Pot-Still-Destillation. Der Begriff stammt aus dem Arabischen (al-anbiq) und geht auf griechische Vorläufer zurück. Auch als [[wiki:pot-still|Pot Still]] bezeichnet." },
      { title: "Alkohol", body: "Im Sinne von Trinkalkohol: Ethanol (C₂H₅OH). Der Begriff \"Alkohol\" wurde von Paracelsus geprägt und bedeutet sinngemäß \"etwas Feines oder Besonderes\". Entstehung durch [[wiki:fermentation|Fermentation]] von Zucker." },
      { title: "Allasch", body: "Hochprozentiger, kümmelbetonter Likör aus Deutschland bzw. dem Baltikum." },
      { title: "Amaretto", body: "Likör aus Bittermandelschalen, Aprikosenkernöl und weiteren Zutaten mit ausgeprägtem Marzipanaroma. Bekanntester Vertreter: Disaronno Originale." },
      { title: "Amari", body: "Oberbegriff für italienische Bitterliköre. Plural von [[wiki:amaro|Amaro]]." },
      { title: "Amaro", body: "Italienisches Bitterspirituose mit Kräutercharakter. Traditionell als [[wiki:digestif|Digestif]] getrunken. Plural: [[wiki:amari|Amari]]." },
      { title: "Añejo", body: "Mexikanische Reifekennzeichnung für [[wiki:mezcal|Mezcal]] und [[wiki:tequila|Tequila]]: mindestens 1 Jahr, maximal 3 Jahre Fasslagerung." },
      { title: "Angel's Share", body: "Der durch Verdunstung beim Fasslager entstehende Alkoholverlust. Typischerweise 2–3 % pro Jahr. Auch als *Part des Anges* (franz.) bezeichnet." },
      { title: "Angostura", body: "Cocktail-[[wiki:bitters|Bitters]] aus Trinidad, benannt nach der venezolanischen Stadt Angostura. Rezeptur seit 1824 in der Familie Siegert. Unverzichtbare Zutat in Klassikern wie [[wiki:old-fashioned|Old Fashioned]] und [[wiki:manhattan|Manhattan]]." },
      { title: "Anisados", body: "Spanische Gruppe anisaromatisierter Spirituosen." },
      { title: "Anisée", body: "Oberbegriff für anisaromatisierte Spirituosen: [[wiki:pastis|Pastis]], [[wiki:ouzo|Ouzo]], [[wiki:arak|Arak]], [[wiki:absinth|Absinth]] und andere." },
      { title: "Anisette", body: "Anislikör mit mildem Geschmack und geringerem Alkoholgehalt als [[wiki:absinth|Absinth]] oder [[wiki:pastis|Pastis]]." },
      { title: "Anker", body: "Historisches europäisches Hohlmaß für Fässer, regional unterschiedlich zwischen 35 und 68 Litern." },
      { title: "Anklatschen", body: "Technik zum Aktivieren von Kräuteraromen durch Aufklatschen der Pflanze in der hohlen Hand. Dabei gehen flüchtige Öle teilweise an die Luft verloren; dennoch wirksam zur Aromafreisetzung." },
      { title: "Aperitif", body: "Getränk vor der Mahlzeit zur Anregung des Appetits. Typische Aperitifs: [[wiki:vermouth|Vermouth]], [[wiki:campari|Campari]], [[wiki:sherry|Sherry]], [[wiki:champagner|Champagner]] oder Aperitif-Cocktails." },
      { title: "Apfelwein", body: "Vergorener Apfelsaft mit 5,5–6,5 % Alkohol. Altes Getränk mit regionalen Bezeichnungen wie [[wiki:ebbelwoi|Ebbelwoi]] (Hessen) oder [[wiki:sidra|Sidra]] (Spanien). Siehe auch [[wiki:cider|Cider]]." },
      { title: "Applejack", body: "Amerikanischer Apfelbrand. Historisch durch Gefrierkonzentration gewonnen (Freeze Distillation), heute meist durch klassische Destillation hergestellt." },
      { title: "Aquavit", body: "Skandinavischer Kräuterschnaps auf Basis von Kümmel und/oder Dill. Name bedeutet \"Lebenswasser\" (lat. *aqua vitae*). Auch: Akvavit." },
      { title: "Arak", body: "Arabischer, anisaromatisierter Schnaps. Klar im Glas, trübt sich (Louche-Effekt) beim Verdünnen mit Wasser. Nicht zu verwechseln mit dem asiatischen [[wiki:arrack|Arrack]]." },
      { title: "Aräometer", body: "Messgerät zur Bestimmung des volumetrischen Alkoholgehalts bei 20 °C. Auch Alkoholspindel genannt." },
      { title: "Armagnac", body: "Französischer Weinbrand aus der Gascogne. Gilt als ältester destillierter Weinbrand Frankreichs. Wird einmalig in der Pot-Still-ähnlichen Armagnac-Brennblase gebrannt." },
      { title: "Arrack", body: "Asiatischer Schnaps aus Palmensaft oder Reis und Zucker. Geschmack zwischen [[wiki:rum|Rum]] und Whiskey. Nicht zu verwechseln mit dem arabischen [[wiki:arak|Arak]]. Wichtige Zutat in historischem [[wiki:punch|Punch]]." },
      { title: "Assemblage", body: "Das Verschneiden von Weinen verschiedener Jahrgänge oder Lagen. Besonders wichtig in der Sektproduktion zur Erzielung eines gleichbleibenden Haustils." },
      { title: "Aufgesetzter", body: "Hausgemachter Schnaps aus Korn und Schwarzen Johannisbeeren, typisch für Rheinland-Westfalen." },
      { title: "Ausgießer", body: "Flaschenaufsatz mit Schnauze für kontrolliertes, tropffreies Ausgießen. Auch [[wiki:pourer|Pourer]] (engl.) genannt." },

      # --- B ---
      { title: "Babbelwasser", body: "Hessischer Volksmund für Apfelwein – abgeleitet von der gesprächig machenden Wirkung des Getränks. Siehe auch [[wiki:ebbelwoi|Ebbelwoi]]." },
      { title: "Bacanora", body: "Mexikanischer Agavenschnaps mit geschützter Herkunftsbezeichnung aus dem Bundesstaat Sonora. Verwandt mit [[wiki:mezcal|Mezcal]]." },
      { title: "Baijiu", body: "Chinesische Getreidebranntwein, häufig aus Hirse. Kann bis zu 60 % Alkohol erreichen. Eines der meistgetrunken Spirituosen der Welt." },
      { title: "Bain-Marie", body: "Wasserbad-Erhitzungsmethode, bei der das Gargut nie über 100 °C erhitzt wird. Wird in der Bar zum schonenden Erwärmen von Zutaten und Sirupen eingesetzt." },
      { title: "Balthazar", body: "Champagnerflasche mit 12 Litern Inhalt." },
      { title: "Barack", body: "Ungarischer Aprikosenbranntwein, im Eichenfass gereift. Unterliegt strengen Herkunftsbezeichnungsregeln. Verwandt mit [[wiki:palinka|Pálinka]]." },
      { title: "Barcaddy", body: "Behälter für Strohhalme, Servietten und weiteres Bar-Zubehör, der auf der Theke aufgestellt wird." },
      { title: "Bärenfang", body: "Ostpreußischer Honiglikör mit geschützter Herkunftsbezeichnung." },
      { title: "Barkeeper", body: "Betreiber oder Angestellter einer Bar; umgangssprachlich auch für [[wiki:bartender|Bartender]] verwendet." },
      { title: "Barlöffel", body: "Langer Rührlöffel für Cocktails und zur Mengenabmessung. Charakteristisch ist der gedrehte Stiel. Wird zum Rühren klarer Drinks und zum sorgfältigen Schichten von Zutaten verwendet. Fasst in der Regel 5 ml. Auch [[wiki:barspoon|Barspoon]] (engl.) genannt." },
      { title: "Barmaid", body: "Weibliche Barkeeperin oder Cocktailmischerin." },
      { title: "Barman", body: "Männlicher Barkeeper oder Cocktailmischer." },
      { title: "Barmatte", body: "Rutschfeste Gummimatte, auf der Gläser und der [[wiki:shaker|Shaker]] abgestellt werden. Fängt Spritzer auf und sorgt für Halt." },
      { title: "Barmesser", body: "Zweizinkiges Messer zum Schneiden und Aufspießen von Früchten." },
      { title: "Barraquito", body: "Traditionelles Heißgetränk der Kanarischen Inseln: Espresso mit Milch, Likör (oft Licor 43), Zitronenzeste, Zimt und Milchschaum." },
      { title: "Barrel Aged", body: "Im Holzfass gereift. Bezeichnet sowohl Spirituosen als auch fertig gemischte Cocktails, die zur Geschmacksentwicklung in Fässern reifen. Siehe auch [[wiki:cocktail-aging|Cocktail Aging]]." },
      { title: "Barrique", body: "Eichenfass mit einem Fassungsvermögen von ca. 225 Litern. Historisches Standardfass für den Weinhandel. Wichtig für die Reifung von [[wiki:cognac|Cognac]], [[wiki:armagnac|Armagnac]], [[wiki:whisky|Whisky]] und anderen Spirituosen." },
      { title: "Barserviette", body: "Kleine Serviette, die unter ein Glas gelegt wird, um Kondenswasser aufzufangen." },
      { title: "Barsieb", body: "Sieb zum Zurückhalten von Eis und Fruchtstücken beim Ausgießen eines Cocktails. Die zwei Haupttypen sind [[wiki:hawthorne-strainer|Hawthorne Strainer]] (mit Federspirale) und [[wiki:julep-strainer|Julep Strainer]] (löffelförmig)." },
      { title: "Barspoon", body: "Englische Bezeichnung für [[wiki:barloffel|Barlöffel]]. Fasst ca. 5 ml." },
      { title: "Bartender", body: "Person, die professionell Cocktails mixt und die Bar betreibt. Umfassenderer Begriff als [[wiki:barkeeper|Barkeeper]]." },
      { title: "Bartowel", body: "Barhantuch zum Trocknen und Polieren von Gläsern." },
      { title: "Barzange", body: "Mehrzweckwerkzeug: Flaschen- und Dosenöffner kombiniert mit Eiszange oder Früchtezange." },
      { title: "Basis", body: "Hauptkomponente eines Cocktails – üblicherweise eine Spirituose. Darauf folgen [[wiki:modifier|Modifier]] und aromatisierende Zutaten (Flavouring Part)." },
      { title: "Batida", body: "Brasilianischer Cocktail aus [[wiki:cachaca|Cachaça]], Fruchtsaft, Zucker und Wasser. Die bekannteste Variante ist die Batida de Côco mit Kokosmilch." },
      { title: "Before-Dinner-Cocktail", body: "Drink vor der Mahlzeit zur Appetitanregung. Synonym für [[wiki:aperitif|Aperitif]]." },
      { title: "Bernhard von Clairvaux", body: "Heiliger Bernhard von Clairvaux (ca. 1090–1153), Schutzpatron der Barkeeper und Gastronomen." },
      { title: "Bianco", body: "Italienische Bezeichnung für Weißwein oder weißen Vermouth." },
      { title: "Bitter Lemon", body: "Kohlensäurehaltiges Erfrischungsgetränk mit Chininsäure aus Zitronensaft. Häufig als Mixer verwendet." },
      { title: "Bitters", body: "Alkoholische, bittere Kräutertinktur, die in kleinen Mengen (Dashes) Cocktails verfeinert. Wichtige Varianten: [[wiki:angostura|Angostura]], Peychaud's, Orange Bitters. Wesentliche Zutat in Klassikern wie [[wiki:old-fashioned|Old Fashioned]] und [[wiki:manhattan|Manhattan]]." },
      { title: "Blanco", body: "Ungereifter, frischer [[wiki:mezcal|Mezcal]] oder [[wiki:tequila|Tequila]]. Spanisch für \"weiß\". Direkt nach der Destillation abgefüllt." },
      { title: "Blazer", body: "Getränkekategorie: Erwärmte Spirituose mit Zucker, Sirup und aromatischen Garnierungen, die dramatisch zwischen zwei Gefäßen flambiert wird. Bekannt gemacht von Barkeeper-Legende Jerry Thomas." },
      { title: "Blender", body: "Elektrisches Mixgerät für Frozen Cocktails und Fruchtzubereitungen." },
      { title: "Blue Curaçao", body: "Blau gefärbter Bitterorangen-Likör auf Basis des [[wiki:curacao|Curaçao]]-Likörs. Erhältlich auch in Grün und Rot. Der blaue Farbton macht ihn zu einem beliebten Cocktailzutat für visuelle Effekte." },
      { title: "Borrel", body: "Traditionelles niederländisches Trinkglas für [[wiki:genever|Genever]]." },
      { title: "Boston-Shaker", body: "Zweiteiliger [[wiki:shaker|Shaker]] aus einem Metallteil und einem Glasteil. Weit verbreitet in der Profibar." },
      { title: "Botanicals", body: "Pflanzenextrakte, Kräuter und Gewürze, die einem Destillat seinen Charakter verleihen. Besonders wichtig bei [[wiki:gin|Gin]], der durch Botanicals sein typisches Juniperus-Profil erhält." },
      { title: "Bourbon", body: "Amerikanischer Maiswhiskey aus mindestens 51 % Mais. Muss in neuen, ausgekohlten Eichenfässern reifen. Typische Aromen: Vanille, Karamell, Eiche." },
      { title: "Brouilleur", body: "Absinth-Zubehör: Ein Gerät, das Wasser tropfenweise in das Glas laufen lässt und so den [[wiki:louche-effekt|Louche-Effekt]] auslöst. Ähnlich wie [[wiki:absinthe-fontaine|Absinthe-Fontaine]], aber kompakter." },
      { title: "Brut", body: "Sehr trockene Schaumweinbezeichnung mit 6–15 g Restzucker pro Liter." },
      { title: "Built in the Glass", body: "Cocktailzubereitungsmethode, bei der alle Zutaten direkt im Serviersglas zusammengestellt werden. Geeignet für gut mischbare Zutaten wie beim [[wiki:negroni|Negroni]] oder [[wiki:old-fashioned|Old Fashioned]]." },

      # --- C ---
      { title: "Cachaça", body: "Brasilianische Spirituose aus frisch gepresstem Zuckerrohrsaft. Basis des [[wiki:caipirinha|Caipirinha]]. Verwandt mit [[wiki:rhum-agricole|Rhum Agricole]], aber mit eigenen Produktionsregeln." },
      { title: "Calvados", body: "Apfelbrand aus der Normandie mit geschützter Herkunftsbezeichnung. Aus Apfel- oder Birnenmost destilliert und in Eichenfässern gereift." },
      { title: "Cask Strength", body: "Fassstärke: Spirituose, die ohne Wasserzusatz direkt aus dem Fass abgefüllt wird. Meist 55–65 % Alkohol. Auch [[wiki:fassstarke|Fassstärke]] genannt." },
      { title: "Cassis", body: "Schwarzer Johannisbeerlikör. Bekannteste Verwendung im [[wiki:kir|Kir]] und [[wiki:kir-royal|Kir Royal]]." },
      { title: "Catavino", body: "Traditionelles spanisches Sherryglas; tulpenförmig mit sich nach oben verjüngendem Rand. Ideal zur Aromakonzentration beim Verkosten." },
      { title: "Cava", body: "Spanischer Schaumwein mit geschützter Herkunftsbezeichnung (DO). Hergestellt nach der klassischen Flaschengärungsmethode." },
      { title: "Champagner", body: "Geschützter Schaumwein aus der Champagne (Frankreich). Hergestellt ausschließlich aus Pinot Noir, Pinot Meunier und Chardonnay nach der Méthode Champenoise." },
      { title: "Chaser", body: "Begleitgetränk zu einem stärkeren Drink – meist ein Bier oder Wasser nach einem Whisky-Shot." },
      { title: "Cheong-Verfahren", body: "Koreanische Kaltextraktionsmethode: Früchte werden im Verhältnis 1:1 mit Zucker angesetzt. Nach Fertigstellung ergibt sich ein konzentrierter, aromenreicher Sirup ohne Erhitzen." },
      { title: "Chinin", body: "Bitteres Alkaloid aus der Rinde des Chinarindenbaums. Findet sich in [[wiki:tonic-water|Tonic Water]] und Bitter-Lemon-Getränken. Verleiht den charakteristischen Bittergeschmack." },
      { title: "Chu Yeh Ching", body: "Chinesischer Bambusblätterlikör in gelbgrüner Farbe, aus über 12 Kräutern hergestellt, ca. 40 % Alkohol." },
      { title: "Cider", body: "Vergorener Apfelsaft. In Deutschland als [[wiki:apfelwein|Apfelwein]] bekannt. Alkoholgehalt variiert je nach Herstellung. Nicht zu verwechseln mit unvergorener \"Apple Cider\" in Amerika." },
      { title: "Clairin", body: "Haitianischer weißer Rhum Agricole aus spontaner Fermentation mit Wildhefen. Typischerweise 51–60 % Alkohol. Gilt als Urform des Rums." },
      { title: "Cobbler", body: "Klassische Cocktailkategorie: Spirituose oder Wein, Fruchtstücke und Zucker, über [[wiki:crushed-ice|Crushed Ice]] serviert. Dekorativ garniert." },
      { title: "Cocktail Aging", body: "Reifung fertiger Cocktails in Holzfässern über Wochen oder Monate. Rundet Aromen ab und verleiht dem Drink Fasscharakter. Auch [[wiki:barrel-aged|Barrel Aged]] Cocktail genannt." },
      { title: "Cocktail-Kultur", body: "Die Kunst und das Ambiente einer gepflegten Bar: elegante Einrichtung, zurückhaltende Musik, höflicher Service und handwerklich exzellente Getränke." },
      { title: "Coffey Still", body: "Säulendestillierapparat (Patentbrennblase), 1831 von Aeneas Coffey patentiert. Ermöglicht kontinuierliche Destillation und wird besonders für [[wiki:grain-whisky|Grain Whisky]] und [[wiki:rum|Rum]] eingesetzt." },
      { title: "Cognac", body: "Französischer Weinbrand aus der Cognac-Region mit geschützter Herkunftsbezeichnung. Aus bestimmten Traubensorten doppelt destilliert und mindestens 2 Jahre in Limousin-Eichenfässern gereift." },
      { title: "Cold Drip", body: "Aroma-Extraktionsmethode: Wasser tropft über Stunden langsam durch Kaffeepulver oder andere Zutaten, ohne Wärme anzuwenden. Ergibt besonders feinaromatische Extrakte." },
      { title: "Collins", body: "Klassische Cocktailkategorie: Spirituose, Zitronensaft, Sirup und Sodawasser im Longdrink-Glas mit Eis. Bekanntester Vertreter: [[wiki:tom-collins|Tom Collins]]." },
      { title: "Coppa", body: "Ballon- oder kelchförmiges Glas, ideal für [[wiki:gin-tonic|Gin Tonic]]. Fasst die Aromen des Gins besonders gut." },
      { title: "Cordial", body: "Digestiflikör, Kräuterlikör oder – im angloamerikanischen Raum – auch Fruchtsirup ohne Alkohol." },
      { title: "Coupette", body: "Cocktailglas in der Form einer Champagner-Coupe: flach, mit breitem Rand und kurzem Stiel. Für Cocktails \"straight up\" (ohne Eis)." },
      { title: "Cracked Ice", body: "Grob gebrochenes Eis aus größeren Eisblöcken. Zwischen [[wiki:ice-cube|Ice Cube]] und [[wiki:crushed-ice|Crushed Ice]]. Wird mit einem [[wiki:eispickel|Eispickel]] hergestellt." },
      { title: "Cream of Coconut", body: "Gesüßte Kokosnusscreme aus Kokosfleisch und -saft. Hauptzutat der [[wiki:pina-colada|Piña Colada]]. Nicht zu verwechseln mit ungesüßter Kokosmilch." },
      { title: "Crémant", body: "Französischer Schaumwein nach der Méthode Champenoise ohne geschützte Herkunftsbezeichnung. Hergestellt in verschiedenen Regionen wie Alsace, Bourgogne oder Loire." },
      { title: "Crème de Cassis", body: "Schwarzer Johannisbeerlikör. Basis für [[wiki:kir|Kir]] und [[wiki:kir-royal|Kir Royal]]. Mindestens 400 g Zucker und 15 % Alkohol." },
      { title: "Crème de Cerises", body: "Kirschlikör." },
      { title: "Crème de Fraise", body: "Erdbeerlikör. Die Variante *Crème de Fraise des Bois* wird aus Walderdbeeren hergestellt." },
      { title: "Crème de Framboise", body: "Himbeerlikör." },
      { title: "Crème de Menthe", body: "Pfefferminzlikör. Erhältlich in Weiß (farbneutral) und Grün. Verwendung u. a. im [[wiki:grasshopper|Grasshopper]]." },
      { title: "Crème de Mûre", body: "Brombeerlikör." },
      { title: "Crème de Myrtille", body: "Heidelbeerlikör." },
      { title: "Crème de Noyaux", body: "Kernlikör aus Aprikosen-, Mandel- oder Pflaumenkernen." },
      { title: "Crème de Pêche", body: "Pfirsichlikör." },
      { title: "Crème de Poire", body: "Birnlikör." },
      { title: "Crème de Violette", body: "Veilchenlikör. Verwendung u. a. im [[wiki:aviation|Aviation]]." },
      { title: "Crème de Yvette", body: "Likör aus Veilchenblüten, Walderdbeeren, Himbeeren, Brombeeren und schwarzen Johannisbeeren. Amerkanischer Klassiker." },
      { title: "Crushed Ice", body: "Gestoßenes oder gemahlenes Eis. Basis für Frozen Drinks und Klassiker wie [[wiki:julep|Julep]] oder [[wiki:caipirinha|Caipirinha]]." },
      { title: "Crusta", body: "Zuckerrand am Glas, erzeugt durch Anfeuchten des Glasrandes mit Zitronensaft oder Likör und Eintauchen in feinen Zucker." },
      { title: "Curaçao", body: "Bitterorangen-Likör aus der Schale der Laraha-Orange von der Insel Curaçao. Erhältlich klar, orange, blau ([[wiki:blue-curacao|Blue Curaçao]]) oder rot. [[wiki:triple-sec|Triple Sec]] ist eine trockene Variante." },

      # --- D ---
      { title: "Daiquiri", body: "Klassischer Kurzdrink aus [[wiki:rum|Rum]], Limettensaft und Zuckersirup. Benannt nach einem Ort in Kuba. Wird geschüttelt und ohne Eis serviert." },
      { title: "Daisy", body: "Klassische Cocktailkategorie: Spirituose, Zitrone, Grenadine oder Likör als Süßungsmittel, serviert über Eis." },
      { title: "Dash", body: "Kleine Einheit für [[wiki:bitters|Bitters]] oder andere Aromatika. Entspricht je nach Viskosität ca. 0,5–1 ml. Wird aus einer Dashflasche oder einem Schüttelröhrchen dosiert." },
      { title: "Defrutum", body: "Nicht vergorener Traubenmost, durch Kochen auf Sirupkonsistenz reduziert. Historische Süßungszutat." },
      { title: "Degorgieren", body: "Entfernen des Hefedepots aus einer Schaumweinflasche. Modern erfolgt dies durch Einfrieren des Flaschenhals und anschließendes Herausschießen des Eispfropfens." },
      { title: "Degustation", body: "Objektive sensorische Bewertung und Qualitätsbeurteilung von Lebensmitteln und Getränken. Umfasst [[wiki:nosing|Nosing]], [[wiki:tasting|Tasting]] und die Beschreibung von Aroma, Geschmack und Abgang." },
      { title: "Dekanter", body: "Bauchige Glaskaraffe zum Belüften und Dekantieren von Wein sowie zur Trennung vom Depot." },
      { title: "Dekantieren", body: "Vorsichtiges Umfüllen von Wein aus der Flasche in den [[wiki:dekanter|Dekanter]], um Sediment zurückzulassen und den Wein zu belüften." },
      { title: "Dekoration", body: "Garnierung eines Cocktails mit Früchten, Zesten, Kräutern oder anderen dekorativen Elementen. Soll sowohl optisch ansprechend als auch aromatisch zum Getränk passen." },
      { title: "Demerara", body: "Historische niederländische Kolonie an der Nordküste Südamerikas (1752–1814), heute Teil von Guyana. Bekannt für den gleichnamigen Zucker und seine Rum-Produktion." },
      { title: "Demerara-Zucker", body: "Hellbrauner Rohrzucker mit großen Kristallen aus der Demerara-Region. Enthält ca. 2–3 % Melasse und verleiht Cocktailsirups eine charakteristische Tiefe." },
      { title: "Demi", body: "Schaumweinflasche mit 0,375 Litern. Auch *Fillette* genannt." },
      { title: "Demi-sec", body: "Halbtrockene Schaumweinbezeichnung mit 35–50 g Restzucker pro Liter." },
      { title: "Destillation", body: "Alkoholgewinnung durch Erhitzen einer vergorenen Maische, Verdampfen des Alkohols und anschließende Kondensation. Grundlage aller Branntweine und Spirituosen." },
      { title: "Digestif", body: "Getränk nach der Mahlzeit zur Unterstützung der Verdauung. Typische Digestifs: [[wiki:amaro|Amaro]], [[wiki:cognac|Cognac]], [[wiki:grappa|Grappa]], [[wiki:calvados|Calvados]], [[wiki:whisky|Whisky]]." },
      { title: "Double Strain", body: "Doppeltes Absieben beim Ausgießen: zunächst durch das [[wiki:barsieb|Barsieb]], dann durch ein feines [[wiki:haarsieb|Haarsieb]], um alle Pflanzen- und Fruchtreste zu entfernen." },
      { title: "Doux", body: "Süße Schaumweinbezeichnung mit mindestens 50 g Restzucker pro Liter." },
      { title: "Dry", body: "Trocken. Bei Spirituosen und Schaumweinen Bezeichnung für geringen Restzuckergehalt. Bei [[wiki:gin|Gin]] oder [[wiki:vermouth|Vermouth]] auch Produktionskennzeichnung." },
      { title: "Dry Shake", body: "Schütteln ohne Eis, um Zutaten wie Eiweiß oder Sahne aufzuschlagen und zu emulgieren, bevor Eis hinzugefügt wird." },
      { title: "Dunder", body: "Rückstand der [[wiki:rum|Rum]]-Destillation, der dem nächsten Ansatz beigefügt wird, um die Fermentation zu fördern und den Geschmack zu intensivieren." },

      # --- E ---
      { title: "Eau de Vie", body: "Destillat aus vergorenem Obst oder Wein. Französisch für \"Lebenswasser\". Oberbegriff für alle klaren Obstbrände wie [[wiki:grappa|Grappa]], [[wiki:calvados|Calvados]] (in der Reifung) oder Kirsch." },
      { title: "Ebbelwoi", body: "Südhessische Bezeichnung für [[wiki:apfelwein|Apfelwein]]. Traditionelles Getränk der Frankfurter Region." },
      { title: "Eggnog", body: "Festliches Getränk aus Eiern, Sahne, Milch, Zucker und Spirituosen (meist [[wiki:rum|Rum]], [[wiki:bourbon|Bourbon]] oder [[wiki:cognac|Cognac]]). In den USA besonders zu Weihnachten populär." },
      { title: "Eierwein", body: "Warmes Gewürzweingetränk mit Eiern und Branntwein. Traditionell zu Silvester und Ostern getrunken." },
      { title: "Eiskübel", body: "Champagnerkühler oder Eisbehälter für die Bararbeit. Dient zur Aufbewahrung von Eiswürfeln und zum Kühlen von Weinflaschen." },
      { title: "Eispickel", body: "Werkzeug zum Brechen von Eis. Erhältlich als Einzel- oder Mehrpunkt-Pickel für unterschiedliche Eisgrößen." },
      { title: "Eisschaufel", body: "Hygienisches Werkzeug zur Entnahme von Eis aus dem Eisbehälter. Direktes Füllen mit der Hand ist unhygienisch." },
      { title: "Eiszange", body: "Hygienische Zange zur portionierten Entnahme von Eiswürfeln." },
      { title: "Elbow-Press", body: "Hebelpresse für Zitrusfrüchte mit Kniehebelmechanismus. Ermöglicht saubere Saftgewinnung ohne Bitterkeit aus der Schale." },
      { title: "Elderflower", body: "Holunderblüte. Aromatische Blüte des Holunderbuschs, verwendet für Likör (z. B. St-Germain) und Sirup. Verleiht Cocktails ein feines florales Aroma." },
      { title: "Enzian", body: "Alpine Bitterspirituose aus der Wurzel des Gelben Enzians (*Gentiana lutea*). Von der UNESCO als immaterielles Kulturerbe anerkannt. Charakteristisch bitterer, erdiger Geschmack." },
      { title: "Espuma", body: "Aromatisierter Schaum, der mittels Siphon schnell hergestellt werden kann. Einsatz als Topping auf Cocktails oder als Texturkomponente bei Molekular-Cocktails. Aus der Molekularküche stammend." },
      { title: "Essenz", body: "Einkomponentiger Extrakt einer einzelnen Zutat. Ähnlich in Aussehen und Verwendung wie [[wiki:bitters|Bitters]], aber einfacher zusammengesetzt." },
      { title: "Extra Añejo", body: "Mexikanische Reifekennzeichnung für [[wiki:mezcal|Mezcal]] und [[wiki:tequila|Tequila]]: mindestens 3 Jahre Fasslagerung." },
      { title: "Extra Sec", body: "\"Extra trocken\": Schaumweinbezeichnung mit 12–20 g Restzucker pro Liter." },

      # --- F ---
      { title: "Fadenschneider", body: "Werkzeug zum Schneiden feiner Zestenstreifen. Auch [[wiki:zestenreisser|Zestenreißer]] oder Channel Knife genannt." },
      { title: "Falernum", body: "Rumlikör mit Limettensaft und Gewürzen (Nelken, Mandel, Ingwer). Wichtige Zutat in Tiki-Cocktails." },
      { title: "Fassstärke", body: "Spirituose, die ohne Wasserzusatz direkt in der Fassstärke abgefüllt wird. Meist 55–65 % Alkohol. Englisch: [[wiki:cask-strength|Cask Strength]]." },
      { title: "Fat Washing", body: "Verfahren zur Aromatisierung von Spirituosen mit Fettanteilen aus geröstetem Fleisch, Nüssen oder Butter. Das Fett wird eingefroren und entfernt, das Aroma bleibt im Destillat." },
      { title: "Federweißer", body: "Frisch angegärter Traubenmost. Enthält noch aktive Hefen und steht unter leichtem CO₂-Druck. Saisonal im Herbst erhältlich. Auch [[wiki:sauser|Sauser]] oder [[wiki:fiederwaissen|Fiederwäissen]] (Luxemburg) genannt." },
      { title: "Fiaker", body: "Österreichisches Heißgetränk: Schwarzer Kaffee mit [[wiki:kirschwasser|Kirschwasser]] und Schlagsahne. Wiener Kaffeehausspezialität." },
      { title: "Filler", body: "Mixer-Getränk, das als Aufguss in Longdrinks dient (z. B. Sodawasser, Tonic Water, Orangensaft). Auch Mixer genannt." },
      { title: "Filz", body: "Papier- oder Kartonuntersetzer für Gläser." },
      { title: "Fino", body: "Trockener [[wiki:sherry|Sherry]] mit biologischer Reifung unter Flor-Hefe. Sehr trockener, heller Stil." },
      { title: "Fix", body: "Historische Cocktailkategorie: Hochprozentige Spirituose, Zitronensaft und bevorzugt Himbeersirup, geschüttelt über [[wiki:crushed-ice|Crushed Ice]]." },
      { title: "Fizz", body: "Cocktailkategorie: Spirituose, Zitronensaft, Zucker und Sodawasser. Ähnlich dem [[wiki:collins|Collins]], aber kürzer. Bekanntester Vertreter: [[wiki:gin-fizz|Gin Fizz]]." },
      { title: "Flairbartending", body: "Spektakuläre Bartenderkunst, bei der Flaschen, [[wiki:shaker|Shaker]] und Gläser jonglierend in die Cocktailzubereitung integriert werden." },
      { title: "Flambieren", body: "Anzünden von Spirituosen beim Servieren. Beim [[wiki:absinth|Absinth]] traditionell umstritten, typisch bei Irish Coffee und [[wiki:feuerzangenbowle|Feuerzangenbowle]]." },
      { title: "Flaschengärung", body: "Sekundärgärung in der verschlossenen Flasche durch Zugabe von Hefe und Zucker. Grundlage der Méthode Champenoise für [[wiki:champagner|Champagner]] und anderen Premium-Schaumweinen." },
      { title: "Flavouring Part", body: "Die aromatisierende Komponente eines Cocktails, die [[wiki:basis|Basis]] und [[wiki:modifier|Modifier]] mit intensiven Aromen in kleinen Mengen perfektioniert (z. B. [[wiki:bitters|Bitters]], [[wiki:sirupe|Sirupe]])." },
      { title: "Flip", body: "Historische Cocktailkategorie: Spirituose oder Wein mit Ei und Zucker, heiß oder kalt serviert." },
      { title: "Floaten", body: "Vorsichtiges Auflegen einer Zutat auf die Oberfläche des Drinks, ohne sie unterzumischen. Ermöglicht optische Schichtungen." },
      { title: "Flöte", body: "Schlankes, langstieligiges Sektglas mit kleiner Öffnung. Hält Kohlensäure länger. Auch Sektkelch genannt." },
      { title: "Foam", body: "Schaum aus Sahne, Eiweiß oder [[wiki:espuma|Espuma]] als obere Schicht eines Cocktails. Entsteht durch intensives Schütteln oder Siphon." },
      { title: "Frappé", body: "Historische Getränkekategorie: Likör, Spirituose, Milch oder Kaffee über [[wiki:crushed-ice|Crushed Ice]], oft mit einem Strohhalm serviert." },
      { title: "Frappieren", body: "Schnelles Abkühlen einer Flüssigkeit durch ein Eisbad mit Salzzusatz." },
      { title: "Frozen", body: "Im Mixer zu einem homogenen Getränk verarbeitete Zutaten mit [[wiki:crushed-ice|Crushed Ice]]. Z. B. Frozen Margarita oder Frozen Daiquiri." },
      { title: "Fruchtpresse", body: "Unverzichtbares Bar-Equipment zum frischen Auspressen von Zitrusfrüchten. Verfügbar als Hebel-, Hand- oder elektrische Presse." },

      # --- G ---
      { title: "Garnitur", body: "Dekorative und aromatische Zugabe zum fertigen Cocktail. Kann frische oder getrocknete Früchte, Zesten, Kräuter oder Essbare Blüten umfassen." },
      { title: "Gastrique", body: "Karamellisierter Zucker mit Essig; aus der Gourmetküche stammende süß-saure Sauce, die auch in Cocktails eingesetzt wird." },
      { title: "Gedeck", body: "Ostdeutsche Getränkekombination: Bier mit Sekt oder Bier mit Schnaps. Regional in zahlreichen Varianten verbreitet." },
      { title: "Gelifikation", body: "Flüssigkeit wird zu Gel verfestigt. Technik der Molekulargastronomie, die auch bei [[wiki:molekular-cocktails|Molekular-Cocktails]] eingesetzt wird. Verwandt mit [[wiki:spharisierung|Sphärisierung]]." },
      { title: "Genever", body: "Niederländischer oder belgischer Wacholderschnaps; historischer Vorläufer des [[wiki:gin|Gin]]. Wird aus Malzwein destilliert und anschließend verschnitten. Zwei Hauptkategorien: Jonge (jünger, neutraler) und Oude (älter, malzbetonter)." },
      { title: "Gibson", body: "Variante des [[wiki:dry-martini|Dry Martini]] mit Cocktailzwiebel statt Olive als Garnierung." },
      { title: "Gill", body: "Amerikanisches Barmaß, entspricht einem Weinglas. Historische Einheit für ca. 120 ml." },
      { title: "Gimlet", body: "Klassischer Kurzdrink aus [[wiki:gin|Gin]] (oder [[wiki:vodka|Vodka]]) und Limettensaft. Traditionell mit [[wiki:rose-s-lime-juice|Rose's Lime Juice]] zubereitet." },
      { title: "Gin", body: "Wacholderbetonte Spirituose auf Basis eines Getreidedestillats. Muss den Geschmack von Wacholder (*Juniperus communis*) aufweisen. Historisch aus dem niederländischen [[wiki:genever|Genever]] entwickelt." },
      { title: "Gin Tonic", body: "Klassischer [[wiki:highball|Highball]] aus [[wiki:gin|Gin]] und [[wiki:tonic-water|Tonic Water]], serviert über Eis. Einer der meistgetrunken Longdrinks der Welt. Traditionell mit einem Limetten- oder Zitronenspalte garniert; in der modernen Gin-Tonic-Kultur mit verschiedensten Botanicals, Früchten und Kräutern verfeinert. Die Wahl des Tonics beeinflusst das Geschmacksprofil erheblich." },
      { title: "Ginger Ale", body: "Kohlensäurehaltiges Ingwer-Erfrischungsgetränk. Milder im Ingwergeschmack als [[wiki:ginger-beer|Ginger Beer]]. Mixer für [[wiki:whisky-ginger|Whisky Ginger]] oder [[wiki:moscow-mule|Moscow Mule]]." },
      { title: "Ginger Beer", body: "Kohlensäurehaltiges Ingwergetränk mit intensiverem Ingwerprofil als [[wiki:ginger-ale|Ginger Ale]]. Meist alkoholfrei. Basis des [[wiki:moscow-mule|Moscow Mule]] und [[wiki:dark-n-stormy|Dark 'n' Stormy]]." },
      { title: "Glencairn", body: "Robustes Nosing-Glas für Whisky mit dickem Boden und sich nach oben verjüngendem Rand. Optimiert für Whisky-Tastings." },
      { title: "Glögg", body: "Skandinavischer Glühwein mit Gewürzen wie Zimt, Kardamom und Nelken. Auch mit Aquavit oder Rum verstärkt. Auch Glögi (Finnland) oder Gløgg (Dänemark) genannt." },
      { title: "Glühwein", body: "Gewürzter, gesüßter und erhitzter Wein. Traditionelles Weihnachtsmarktgetränk." },
      { title: "Goblet", body: "Kelchglas mit breiter Öffnung. Für bestimmte Bier- und Cocktailstile verwendet." },
      { title: "Gomme Syrup", body: "Zuckersirup mit Gummi arabicum. Das Gummi arabicum verleiht dem Sirup eine seidigere Textur und verbessert das Mundgefühl des Cocktails. Auch [[wiki:sirop-de-gomme|Sirop de Gomme]] (franz.)." },
      { title: "Grappa", body: "Italienischer Tresterbrand aus den Rückständen der Weinproduktion (Trester). Geschütztes italienisches Produkt." },
      { title: "Grenadine", body: "Roter Fruchtsirup, ursprünglich aus Granatapfelsaft. Wird in vielen klassischen Cocktails als Süßungs- und Farbmittel eingesetzt (z. B. [[wiki:shirley-temple|Shirley Temple]], [[wiki:tequila-sunrise|Tequila Sunrise]])." },
      { title: "Grog", body: "Historische Getränkekategorie: [[wiki:rum|Rum]] mit heißem Wasser. Traditionell auch mit Zitrone, Zucker, Gewürzen und Früchten zubereitet. Bezeichnet nach Admiral Vernon (Spitzname \"Old Grog\")." },
      { title: "Gunpowder Proof", body: "Historische britische Alkoholstärkemessung: 57,15 % Alkohol, da bei dieser Stärke Schießpulver, das mit dem Alkohol befeuchtet wurde, gerade noch zündete. Entspricht heute 100 Degrees Proof." },

      # --- H ---
      { title: "Haarsieb", body: "Feines Metallsieb für den [[wiki:double-strain|Double Strain]]. Hält feinste Fruchtreste und Kräuterpartikel zurück." },
      { title: "Hawthorne Strainer", body: "Barsieb mit Federspirale, die es am Shaker oder Rührglas hält. Lässt sich eng oder weit einstellen. Häufigster Siebtyp in der Profibar. Siehe auch [[wiki:barsieb|Barsieb]]." },
      { title: "Herzstück", body: "Mittellauf der Destillation – der wertvollste und aromatischste Teil. Vor- und Nachlauf werden abgetrennt." },
      { title: "Highball", body: "Longdrink aus einer Spirituose und einem Softdrink oder Mixer, serviert im Highball-Glas mit viel Eis. Klassiker: [[wiki:whisky-soda|Whisky Soda]], [[wiki:gin-tonic|Gin Tonic]], [[wiki:rum-cola|Rum Cola]]." },
      { title: "Hogshead", body: "Fassgröße von ca. 250 Litern. Häufig verwendetes Fass in der [[wiki:whisky|Whisky]]-Produktion, vor allem in Schottland." },
      { title: "Hypocras", body: "Mittelalterliches Gewürzwein-Getränk mit Honig oder Zucker und diversen Gewürzen. Ähnelt modernem [[wiki:gluhwein|Glühwein]]. Basler Tradition bewahrt das Rezept. Auch Ypocras oder Ipocras genannt." },

      # --- I ---
      { title: "IBA", body: "International Bartenders Association – die weltweit wichtigste Bartender-Organisation. Definiert offizielle Cocktailrezepturen und veranstaltet internationale Wettbewerbe." },
      { title: "Ice Crusher", body: "Mechanisches oder elektrisches Gerät zur Herstellung von [[wiki:crushed-ice|Crushed Ice]] aus Eiswürfeln." },
      { title: "Infusion", body: "Aromatisierung einer Flüssigkeit durch Einlegen von Früchten, Kräutern, Gewürzen oder Tee. Dauer und Temperatur bestimmen die Intensität. Auch Mazeration oder [[wiki:maceration|Maceration]] genannt." },
      { title: "Invertzucker", body: "Gemisch aus Glukose und Fruktose, entstanden durch die Spaltung von Saccharose. Süßer als normaler Zucker, kristallisiert nicht. Wird in manchen Sirups verwendet." },

      # --- J ---
      { title: "Jenever", body: "Siehe [[wiki:genever|Genever]]." },
      { title: "Jerez", body: "Andalusische Weinregion in Spanien; Herkunft des [[wiki:sherry|Sherry]]. Auch Xerez oder Xérès." },
      { title: "Jeroboam", body: "Schaumweinflasche mit 3 Litern Inhalt. Auch Doppelmagnum." },
      { title: "Jigger", body: "Messbecher für Spirituosen. Als amerikanisches Slangwort bezeichnet 1 Jigger = 1,5 oz (ca. 4,4 cl). Das Messwerkzeug selbst ist meist doppelseitig mit 4 cl und 2 cl." },
      { title: "Joven", body: "Ungereifter [[wiki:mezcal|Mezcal]] oder [[wiki:tequila|Tequila]]. Gelegentlich mit gereiftem Destillat verschnitten." },
      { title: "Juice", body: "Fruchtsaft. In der Bararbeit möglichst frisch gepresst verwenden. Wichtigste Säfte: Limetten-, Zitronen- und Orangensaft." },
      { title: "Julep", body: "Klassische Cocktailkategorie: Spirituose (meist [[wiki:bourbon|Bourbon]]), Minze, Zucker und [[wiki:crushed-ice|Crushed Ice]] im Julep Mug. Bekanntester Vertreter: [[wiki:mint-julep|Mint Julep]]." },
      { title: "Julep Mug", body: "Silbernes oder verzinntes Metallgefäß zur Zubereitung und zum Servieren eines [[wiki:julep|Julep]]." },
      { title: "Julep Strainer", body: "Löffelförmiges [[wiki:barsieb|Barsieb]] ohne Federspirale. Für Rührgläser geeignet. Klassisches Sieb für geklärte Drinks." },
      { title: "Julienne", body: "Fein geschnittene Obststreifen als Garnitur." },
      { title: "Julienneschneider", body: "Werkzeug zum Schneiden von Gemüse und Obst in feine Streifen (Julienne)." },

      # --- K ---
      { title: "Kapselheber", body: "Kronkorken-Öffner." },
      { title: "Karaffe", body: "Gut geformtes Glasbehältnis mit oder ohne Glasstopfen zur Präsentation von Wein oder Wasser am Tisch." },
      { title: "Kellnerbesteck", body: "Kombinations-Korkenzieher mit Hebelmechanismus für einfaches Entkorken. Standardwerkzeug in der Gastronomie." },
      { title: "Korinthenbrand", body: "Spirituose ausschließlich aus Korinthenrosinen destilliert. Griechischer Raisinbrand mit geschützter Bezeichnung." },
      { title: "Korkenzieher", body: "Werkzeug zum Entfernen von Korken aus Weinflaschen. Verfügbar in vielen Ausführungen: einfache Spirale, Kellnerbesteck, Ah-So-Öffner." },
      { title: "Kracherl", body: "Bayerische und österreichische Bezeichnung für Limonade." },
      { title: "Kugelausstecher", body: "Halbkugelförmiges Werkzeug zum Ausstechen von Obstbällchen. Auch Pariser Messer oder Melonenausstecher genannt." },

      # --- L ---
      { title: "Läuterzucker", body: "Zuckersirup aus aufgelöstem Zucker und Wasser. Standardverhältnis 1:1 ([[wiki:simple-syrup|Simple Syrup]]) oder 2:1 ([[wiki:rich-syrup|Rich Syrup]]). Grundlage vieler Cocktailsirups." },
      { title: "Lewis Bag", body: "Leinenbeutel zur Herstellung von [[wiki:crushed-ice|Crushed Ice]]: Eiswürfel werden in den Beutel gegeben und mit einem Schlegel zerschlagen. Das Leinen absorbiert Schmelzwasser." },
      { title: "Likör", body: "Spirituose mit hohem Zuckergehalt (mindestens 100 g/l in der EU) in verschiedensten Geschmacksrichtungen. Mindestalkoholgehalt 15 %. Basis für viele Cocktails." },
      { title: "Limonade", body: "Erfrischungsgetränk aus Wasser, Zucker und Zitronensaft. Seit dem 17. Jahrhundert bekannt. Heute auch als Oberbegriff für Softdrinks." },
      { title: "Liquid Smoke", body: "Rauchessenz aus der Verbrennung von Holz oder Pflanzen, in Flüssigkeit aufgefangen. Wird in Küche und Bar zur Verleihung von Raucharomen eingesetzt." },
      { title: "Longdrink", body: "Getränk mit wenigen Zutaten und mehr als 18–20 cl Volumen. Meist Spirituose mit einem Mixer wie Sodawasser oder Tonic Water." },
      { title: "Louche-Effekt", body: "Milchige Eintrübung in Anisgeistern ([[wiki:absinth|Absinth]], [[wiki:pastis|Pastis]], [[wiki:ouzo|Ouzo]]) bei Wasserzugabe oder Kühlung. Entsteht durch Ausfällung von Anisöl-Emulsionen. Auch Ouzo-Effekt genannt." },

      # --- M ---
      { title: "Magnum", body: "Schaumweinflasche mit 1,5 Litern Inhalt." },
      { title: "Maische", body: "Vergärungsansatz bei der Herstellung von Whisky, Wein, Bier oder Obstbrand. Enthält Wasser, zuckerhaltige Stärkeprodukte und Hefe." },
      { title: "Malt", body: "Malzwhisky: aus einer einzigen Brennerei und ausschließlich aus gemälzter Gerste hergestellt. Hochwertigste Whiskykategorie. Als [[wiki:single-malt|Single Malt]] bezeichnet." },
      { title: "Mälzen", body: "Prozess der Getreidemälzung: Gerste keimt und wird dann gedarrt (getrocknet), um Enzyme zu aktivieren, die Stärke in vergärbare Zucker umwandeln." },
      { title: "Mandelsirup", body: "Siehe [[wiki:orgeat|Orgeat]]." },
      { title: "Maraschino", body: "Likör aus Marasca-Kirschen mit mindestens 24 % Alkohol. Intensiv aromatisch. Wichtige Zutat in Klassikern wie [[wiki:hemingway-daiquiri|Hemingway Daiquiri]], [[wiki:last-word|Last Word]] und [[wiki:aviation|Aviation]]." },
      { title: "Margarita", body: "Tequila-Cocktail aus [[wiki:tequila|Tequila]], [[wiki:triple-sec|Triple Sec]] und Limettensaft. Meist mit Salzrand serviert. Eine der weltweit meistbestellten Cocktails." },
      { title: "Martini", body: "Klassischer Kurzdrink aus [[wiki:gin|Gin]] oder [[wiki:vodka|Vodka]] mit [[wiki:vermouth|Vermouth]] und optionalen [[wiki:bitters|Bitters]], serviert im [[wiki:cocktailspitz|Cocktailspitz]]. Einer der ältesten und bekanntesten Cocktails." },
      { title: "Matcha", body: "Japanisches grünes Teepulver. Verleiht Cocktails ein erdiges, herbes Aroma mit leuchtend grüner Farbe." },
      { title: "Melasse", body: "Dunkler Sirup als Nebenprodukt der Zuckerproduktion aus Zuckerrohr oder Rüben. Wichtigste Rohstoffbasis für viele [[wiki:rum|Rum]]-Sorten." },
      { title: "Met", body: "Honig-Wasser-Fermentationsgetränk mit 11–20 % Alkohol. Eines der ältesten alkoholischen Getränke der Menschheit. Auch Honigwein genannt." },
      { title: "Mezcal", body: "Mexikanischer Agavenbrand als Oberbegriff, der auch [[wiki:tequila|Tequila]] einschließt. Wird aus verschiedenen Agavenarten gewonnen. Charakteristisch ist oft der Rauchgeschmack durch das Garen der Agavenherzen in Erdöfen." },
      { title: "Mimosa", body: "Klassischer Brunchcocktail aus gleichen Teilen [[wiki:champagner|Champagner]] (oder Sekt) und frisch gepresstem Orangensaft." },
      { title: "Mocktail", body: "Alkoholfreier Cocktail, der optisch und geschmacklich einem alkoholischen Cocktail nachempfunden ist. Auch \"Virgin\"-Cocktail genannt. Siehe auch [[wiki:af-cocktail|AF-Cocktail]]." },
      { title: "Modifier", body: "Sekundäre Cocktailkomponente, die die [[wiki:basis|Basis]] ergänzt und moduliert. Meist ein [[wiki:vermouth|Vermouth]], Likör oder aromatisches Destillat." },
      { title: "Molekular-Cocktail", body: "Cocktail, der mit Techniken der Molekulargastronomie hergestellt wird: [[wiki:spharisierung|Sphärisierung]], [[wiki:gelifikation|Gelifikation]], [[wiki:espuma|Espuma]], [[wiki:liquid-smoke|Liquid Smoke]]. Zielt auf ungewöhnliche Texturen und Präsentationen." },
      { title: "Monolith-Eis", body: "Große, einzelne Eisblöcke, die speziell für ein Glas zugeschnitten werden. Niedrige Oberfläche bedeutet langsames Schmelzen und geringere Verwässerung." },
      { title: "Muddler", body: "Stößel zum Zerdrücken von Früchten, Kräutern und Zuckerwürfeln im Glas oder Shaker. Deutsch: [[wiki:stossel|Stößel]]." },
      { title: "Mule", body: "Cocktailkategorie: Spirituose mit [[wiki:ginger-beer|Ginger Beer]] und Limettensaft, serviert im Kupferbecher. Bekannteste Variante: [[wiki:moscow-mule|Moscow Mule]] mit [[wiki:vodka|Vodka]]." },

      # --- N ---
      { title: "Navy Strength", body: "Britische Militärbezeichnung für Spirituosen mit mindestens 54,5 % Alkohol ([[wiki:gunpowder-proof|Gunpowder Proof]]). Häufig bei [[wiki:rum|Rum]] und [[wiki:gin|Gin]] verwendet." },
      { title: "Neat", body: "Spirituose pur serviert: ohne Eis, ohne Wasser, ohne Mixer. Bei [[wiki:whisky|Whisky]] und [[wiki:cognac|Cognac]] verbreitet." },
      { title: "Negus", body: "Historisches Heißgetränk aus Portwein, Gewürzen, Wasser und Zucker." },
      { title: "Nick & Nora", body: "Elegantes Cocktailglas mit 12–18 cl Fassungsvermögen, ähnlich einem breiten Weinglas ohne Stiel. 1930er-Jahre-Stil, benannt nach den Charakteren aus \"The Thin Man\"." },
      { title: "Nosing", body: "Aromabeurteilung beim Verkosten: Geruchseindrücke werden vor dem eigentlichen Trinken im Nosing-Glas beurteilt. Geht dem [[wiki:tasting|Tasting]] voraus." },

      # --- O ---
      { title: "Old Fashioned", body: "Einer der ältesten Cocktailklassiker: [[wiki:bourbon|Bourbon]] oder [[wiki:rye-whiskey|Rye Whiskey]], Zuckerwürfel, [[wiki:angostura-bitters|Angostura Bitters]] und ein Spritzer Wasser, im Glas angerührt und mit Orangenzeste garniert." },
      { title: "Old Tom", body: "Leicht gesüßter [[wiki:gin|Gin]] aus der frühen Destillationszeit, als schlechtere Techniken mit Süßung kaschiert wurden. Heute als historische Stilkategorie wiederbelebt." },
      { title: "Oleo Saccharum", body: "Extrakt ätherischer Öle aus Zitrusfrüchten durch Einreiben von Zuckerwürfeln oder durch Bedecken der Schalen mit Zucker. Basis für [[wiki:sherbet|Sherbet]] und Punschsirups." },
      { title: "On the Rocks", body: "Getränk auf Eis serviert: direkt über große Eiswürfel oder [[wiki:monolith-eis|Monolith-Eis]] gegossen." },
      { title: "Orgeat", body: "Mandel-Bitteramandel-Sirup mit Zucker und optional Rum und Orangenblütenwasser. Unverzichtbare Zutat im [[wiki:mai-tai|Mai Tai]] und anderen Tiki-Cocktails." },
      { title: "Ouzo", body: "Griechischer Anisschnaps. Trübt sich bei Wasserzugabe ([[wiki:louche-effekt|Louche-Effekt]]). Traditionell mit Wasser und Eis in einem separaten Glas serviert." },
      { title: "Overproof", body: "Bezeichnung für Spirituosen mit außergewöhnlich hohem Alkoholgehalt. Bei [[wiki:rum|Rum]] ab 57,15 % ([[wiki:navy-strength|Navy Strength]]). Overproof Rums können bis zu 75 % erreichen." },

      # --- P ---
      { title: "Pacharán", body: "Spanischer Schlehenschnaps mit über 500-jähriger Tradition aus Navarra. Schlehen werden in [[wiki:anisette|Anisette]] mazeriert. Auch Patxaran genannt." },
      { title: "Pálinka", body: "Geschützter ungarischer Obstbrand mit strengen Herkunfts-, Produktions- und Abfüllvorschriften. Muss in Ungarn aus ungarischen Früchten hergestellt werden. 37,5–55 % Alkohol." },
      { title: "Parfait d'Amour", body: "Veilchenfarbener Likör mit Zitrus- und Veilchennoten. Intensiver als [[wiki:creme-de-violette|Crème de Violette]]." },
      { title: "Pastis", body: "Französischer Anisschnaps, nach dem Absinthverbot in den 1920er Jahren als Alternative entwickelt. Weicher und süßer als [[wiki:absinth|Absinth]], ohne Thujon." },
      { title: "Peated", body: "Torfgeräucherter Whisky, dessen Malz über Torffeuern getrocknet wurde. Typisch für isläydische und bestimmte schottische Whiskys. Der Torfcharakter variiert je nach Herkunft des Torfs." },
      { title: "Peg", body: "Indisches Barmaß. Ein kleines Peg entspricht 30 ml, ein großes Peg 60 ml." },
      { title: "Pimento Dram", body: "Gewürzter Rumlikör mit Piment (Allspice). Wichtige Zutat in Tiki-Cocktails." },
      { title: "Pisco", body: "Südamerikanischer Weinbrand aus Peru oder Chile mit geschützter Herkunftsbezeichnung. Aus speziellen Traubensorten destilliert, ungereift oder kurz in Ton- oder Stahlfässern gelagert." },
      { title: "Poncha", body: "Geschütztes traditionelles Getränk aus Madeira: Zitronensaft, Honig und frischer Zuckerrohrschnaps (Aguardente) zu ungefähr gleichen Teilen." },
      { title: "Port", body: "Apéritif-Wein aus der geschützten Porto-Region an der Mündung des Douro. Fermentation wird durch Zugabe von Hochprozentigem gestoppt; anschließend Fassreifung. Portwein." },
      { title: "Pouring", body: "Zeitbasierte Mengenmessung: Beim Ausgießen wird die Menge durch Zählen der Sekunden geschätzt. Faustformel: ca. 1 cl pro Sekunde. Ungenauer als der [[wiki:jigger|Jigger]]." },
      { title: "Pousse Café", body: "Geschichteter Cocktail: Zutaten werden der Reihe nach – geordnet nach ihrer Dichte – übereinandergeschichtet, ohne sich zu vermischen." },
      { title: "Proof", body: "Historisches amerikanisches Maß für den Alkoholgehalt: 80 Proof = 40 % Vol.; 151 Proof = 75,5 % Vol. Britisch: 100 Degrees Proof = 57,15 % Vol. ([[wiki:gunpowder-proof|Gunpowder Proof]])." },
      { title: "Pulque", body: "Über 2000 Jahre altes, fermentiertes Agavensaftgetränk mit 5–10 % Alkohol. Vorläufer von [[wiki:mezcal|Mezcal]] und [[wiki:tequila|Tequila]]. Heute noch in Mexiko traditionell getrunken." },
      { title: "Punch", body: "Indisch-britische Urform eines gemischten Getränks aus fünf Zutaten: [[wiki:arrack|Arrack]], Zitrone, Tee oder Wasser, Zucker und Gewürze. Heute meist mit [[wiki:rum|Rum]] zubereitet." },
      { title: "Pyment", body: "Honigwein aus vergorenem Traubenmost. Verbindung von [[wiki:met|Met]] und Wein." },

      # --- Q ---
      { title: "Quarter Cask", body: "Kleines Fass mit ca. 45–80 Litern Inhalt (ca. 25 % eines Standard-Barrique). Intensiverer Holzkontakt führt zu schnellerer Reifung." },
      { title: "Queimada", body: "Spanisches Heißgetränk aus Trestergeist (meist galicischer Orujo) und Zucker, flambiert und mit Gewürzen und Früchten verfeinert." },
      { title: "Quinado", body: "Chinarinden-aromatisierter Dessertwein, hergestellt ähnlich wie [[wiki:port|Port]] oder [[wiki:sherry|Sherry]]." },

      # --- R ---
      { title: "Raicilla", body: "Mexikanischer Agavenbrand aus verschiedenen Agavenarten. Alternative zu [[wiki:mezcal|Mezcal]] mit eigenem Produktionsprofil." },
      { title: "Raki", body: "Türkischer Anisschnaps. Trübt sich bei Wasserzugabe ([[wiki:louche-effekt|Louche-Effekt]]). Traditionell \"Löwenmilch\" (Arslan sütü) genannt." },
      { title: "Ratafia", body: "Aperitif aus Branntwein und Traubenmost. Regional auch als Likör auf Fruchtbasis." },
      { title: "Reposado", body: "Mexikanische Reifekennzeichnung für [[wiki:mezcal|Mezcal]] und [[wiki:tequila|Tequila]]: 2 Monate bis 1 Jahr Fasslagerung." },
      { title: "Rich Syrup", body: "Zuckersirup im Verhältnis 2:1 (zwei Teile Zucker, ein Teil Wasser). Süßer und dichter als [[wiki:simple-syrup|Simple Syrup]]." },
      { title: "Rickey", body: "Historische Cocktailkategorie: Spirituose (klassisch [[wiki:gin|Gin]]), halbe Limette, optional Zucker oder Sirup, aufgefüllt mit Sodawasser im Highball-Glas über Eis." },
      { title: "Rohrzucker", body: "Chemisch identisch mit Rübenzucker (Saccharose), aus Zuckerrohr gewonnen. Als brauner oder weißer Zucker erhältlich." },
      { title: "Rosolio", body: "Likör aus gleichen Teilen Alkohol, Wasser und Zucker, abgerundet mit Rosenwasser. Historisch einer der ältesten Liköre Italiens." },
      { title: "Rühr-Becher", body: "Klares Mischgefäß mit Ausgießlippe zum Rühren von Cocktails. Wird für geklärte Drinks wie [[wiki:martini|Martini]] oder [[wiki:negroni|Negroni]] verwendet." },
      { title: "Runny Honey", body: "Dünn gerührter Honig (2 Teile Honig : 1 Teil heißes Wasser), der sich leicht in Cocktails einarbeiten lässt." },
      { title: "Rye Whiskey", body: "Amerikanischer Whiskey mit mindestens 51 % Roggenanteil in der Getreidemischung. Würziger, trockener Charakter. Klassische Basis für [[wiki:manhattan|Manhattan]] und [[wiki:old-fashioned|Old Fashioned]]." },

      # --- S ---
      { title: "Sake", body: "Japanisches Reiswein-Getränk mit 14–16 % Alkohol. Hergestellt durch einen komplexen Gärprozess mit Koji-Schimmelpilz. In verschiedenen Stilen von trocken bis süß erhältlich." },
      { title: "Salmanazar", body: "Champagnerflasche mit 9 Litern Inhalt." },
      { title: "Sambuca", body: "Italienischer Anislikör als [[wiki:digestif|Digestif]]. Traditionell mit drei Kaffeebohnen serviert (*Con la Mosca* – \"mit der Fliege\")." },
      { title: "Sangaree", body: "Historische Cocktailkategorie: Rotwein oder Portwein mit hochprozentigem Destillat, Likör oder Zucker, warm oder eisgekühlt mit Muskatnuss." },
      { title: "Sauser", body: "Teilweise vergorener Traubenmost. Enthält noch aktive Hefen. Saisonal im Herbst erhältlich. Auch [[wiki:federweisser|Federweißer]] oder [[wiki:fiederwaissen|Fiederwäissen]] genannt." },
      { title: "Scaffa", body: "Historische Cocktailkategorie: Hochprozentige Spirituose, Likör und [[wiki:bitters|Bitters]] bei Zimmertemperatur im Kelchglas serviert – ohne Eis." },
      { title: "Schnaps", body: "Umgangssprachliche Bezeichnung für Spirituosen. In der EU Mindestalkoholgehalt von 15 %. Im deutschen Sprachraum oft für Obstbrände verwendet." },
      { title: "Schorle", body: "Mischgetränk aus Wein und Wasser oder Mineralwasser/Soda." },
      { title: "Scotch", body: "Schottischer Whisky. Muss in Schottland aus Wasser und Malzgerste (bei Single Malt) oder Getreide (bei Grain Whisky) hergestellt und mindestens 3 Jahre in Eichenfässern gereift sein." },
      { title: "Shaker", body: "Mischgefäß für Cocktails, die geschüttelt werden sollen. Haupttypen: [[wiki:boston-shaker|Boston-Shaker]] (zweiteilig) und Cobbler Shaker (dreiteilig mit integriertem Sieb)." },
      { title: "Sherbet", body: "Fruchtaromatisierter Sirup auf Basis von [[wiki:oleo-saccharum|Oleo Saccharum]]. Reichhaltigeres Aroma als gewöhnlicher Sirup durch den Gehalt ätherischer Öle." },
      { title: "Sherry", body: "Spanischer Aperitifwein aus der Jerez-Region ([[wiki:jerez|Jerez]]). Durch Solera-Reifung und Aufspriten charakterisiert. Stile reichen von sehr trocken ([[wiki:fino|Fino]]) bis sehr süß (Pedro Ximénez)." },
      { title: "Shooter", body: "Kleiner Cocktail (meist 2–4 cl) in einem Schnapsglas, der auf Ex getrunken wird. Kann geschichtet ([[wiki:pousse-cafe|Pousse Café]]) oder einfach serviert werden." },
      { title: "Shortdrink", body: "Kurzer Cocktail mit ca. 7 cl Inhalt, meist ohne Eis oder nur mit wenig Eis serviert. Gegenteil des [[wiki:longdrink|Longdrink]]." },
      { title: "Shrub", body: "Historische Kategorie: Mazerationsgetränk aus Früchten, Spirituosen und Zucker, optional mit Essig. Heiß oder kalt serviert. Im Cocktailbereich wiederentdeckt als Sirup-Alternative." },
      { title: "Simple Syrup", body: "Zuckersirup im Verhältnis 1:1 (gleiche Teile Zucker und Wasser). Standardmäßig verwendeter [[wiki:lauterzucker|Läuterzucker]] in der Bar." },
      { title: "Singani", body: "Bolivianischer Weinbrand aus Muskat-Alexandre-Trauben mit geschützter Herkunftsbezeichnung. Ähnlich wie [[wiki:pisco|Pisco]], aber mit eigenem regionalen Charakter." },
      { title: "Single Malt", body: "Whisky einer einzigen Brennerei, ausschließlich aus gemälzter Gerste hergestellt. Höchste Whiskykategorie. Siehe auch [[wiki:malt|Malt]]." },
      { title: "Sirop de Canne", body: "Rohrzuckersirup; hellbrauner [[wiki:lauterzucker|Läuterzucker]] aus rohem Zuckerrohr. Alternative zu einfachem Zuckersirup mit karamelligem Unterton." },
      { title: "Sirop de Gomme", body: "Siehe [[wiki:gomme-syrup|Gomme Syrup]]." },
      { title: "Sling", body: "Klassische Cocktailkategorie: Spirituose, Wasser, Zucker und Bitters. Moderner: Fruchtsaft und Soda statt Wasser." },
      { title: "Sliwowitz", body: "Pflaumenschnaps (Obstbrand aus Zwetschen). Traditionell in Osteuropa verbreitet. Auch Slivovic oder Slibowitz geschrieben." },
      { title: "Smash", body: "Cocktailkategorie ähnlich dem [[wiki:julep|Julep]]: Spirituose, frische Minze oder andere Kräuter, Zitronensaft und Zucker, über [[wiki:crushed-ice|Crushed Ice]] serviert." },
      { title: "Smoked Cocktail", body: "Cocktail, der durch Rauch von verbrannten Kräutern, Holzspänen oder Teeblättern aromatisiert wird. Der Rauch wird im Glas oder im [[wiki:shaker|Shaker]] eingefangen." },
      { title: "Snifter", body: "Elegantes, geschwenktes Nosing-Glas für [[wiki:whisky|Whisky]], [[wiki:cognac|Cognac]] und andere hochwertige Spirituosen." },
      { title: "Sodawasser", body: "Mit CO₂ angereichertes Wasser mit Natriumbikarbonat. In Deutschland gesetzlich mindestens 570 mg Natrium pro Liter. Wichtiger [[wiki:filler|Filler]] in vielen Cocktails." },
      { title: "Solera", body: "Traditionelles System der kontinuierlichen Fassreifung für [[wiki:rum|Rum]], [[wiki:sherry|Sherry]], [[wiki:cognac|Cognac]] und andere Spirituosen. Älterer Jahrgang wird ständig mit jüngerem Destillat aufgefüllt." },
      { title: "Sotol", body: "Mexikanischer Brand aus der Sotol-Pflanze (*Dasylirion*), die der Agave ähnelt. Mit geschützter Herkunftsbezeichnung aus drei Bundesstaaten." },
      { title: "Sour", body: "Grundlegende Cocktailkategorie: Spirituose, Zitronensaft und Süßungsmittel. Oft mit Eiweiß geschüttelt. Beispiele: [[wiki:pisco-sour|Pisco Sour]], [[wiki:whiskey-sour|Whiskey Sour]], [[wiki:amaretto-sour|Amaretto Sour]]." },
      { title: "Sphärisierung", body: "Molekulartechnik zur Herstellung flüssigkeitsgefüllter Kugeln (\"Kaviar-Perlen\"). Die Flüssigkeit wird in eine Alginat-Kalziumlactat-Hülle eingeschlossen. Teilweise der [[wiki:molekular-cocktail|Molekular-Cocktail]]." },
      { title: "Spherical Ice", body: "Große Eiskugeln mit geringer Oberfläche. Schmelzen langsamer als normale Eiswürfel und verwässern den Drink weniger. Ideal für Shortdrinks wie [[wiki:old-fashioned|Old Fashioned]] oder [[wiki:negroni|Negroni]]." },
      { title: "Speedrack", body: "Flaschenhalter unterhalb der Theke für die meistgenutzten Spirituosen und Filler." },
      { title: "Spontangärung", body: "Natürliche Gärung ohne Zugabe von Reinzuchthefe, nur durch wilde Hefen aus der Luft und der Umgebung. Besonders bei [[wiki:clairin|Clairin]] und Naturweinen. Verleiht unverwechselbare, komplexe Aromen." },
      { title: "Stößel", body: "Holz- oder Metallwerkzeug zum Zerdrücken von Früchten, Kräutern und Zucker im Glas. Englisch: [[wiki:muddler|Muddler]]." },

      # --- T ---
      { title: "Tankard", body: "Einfaches Trinkgefäß, meist aus Metall. Für andere Gläsertypen siehe Gläserkunde." },
      { title: "Tannine", body: "Phenolische Verbindungen aus Pflanzenmaterial, besonders aus Traubenschalen und Holz. Sorgen für Adstringenz im Wein und tragen zur Reifefähigkeit bei." },
      { title: "Tasting", body: "Sensorische Beurteilungsphase nach dem [[wiki:nosing|Nosing]]: Geschmacks- und Textureindrücke werden bewertet." },
      { title: "Tequila", body: "Mexikanischer Agavenbrand aus der blauen Weber-Agave (*Agave tequilana*) aus der Region Jalisco. Reifekategorien: [[wiki:blanco|Blanco]], [[wiki:reposado|Reposado]], [[wiki:anejo|Añejo]], [[wiki:extra-anejo|Extra Añejo]]. Untergruppe von [[wiki:mezcal|Mezcal]]." },
      { title: "Thiole", body: "Flüchtige organische Schwefelverbindungen, die sich während und nach der Fermentation bilden. Einige sind erwünscht (tropische Aromen), viele nicht." },
      { title: "Thujon", body: "Hauptwirkstoff der grünen ätherischen Öle in Wermut und ähnlichen Pflanzen. Erzeugt bitteren Geschmack. Früher verantwortlich gemacht für die psychoaktive Wirkung des [[wiki:absinth|Absinth]]." },
      { title: "Tiki-Ära", body: "Kulturperiode von etwa 1935 bis in die 1960er Jahre, geprägt durch Tiki-Restaurants und -Bars. Heimat rum-basierter Cocktails wie [[wiki:mai-tai|Mai Tai]], [[wiki:zombie|Zombie]] und [[wiki:painkiller|Painkiller]]." },
      { title: "Tiki-Mug", body: "Trinkgefäß oder Becher mit traditionellen südpazifischen Tiki-Motiven. Typisch für die Tiki-Kultur und Tiki-Cocktails." },
      { title: "Ti Punch", body: "Kleiner Punch (\"Ti\" = \"Petit\") aus der Karibik: [[wiki:rhum-agricole|Rhum Agricole]], Rohrzucker und Limette. Nationaler Cocktail von Martinique." },
      { title: "Toast", body: "Kurze Ansprache beim Erheben der Gläser auf eine Person oder ein Ereignis." },
      { title: "Toasting", body: "Das Ausrösten der Fassinnenseite zur Geschmacksimpartierung. Entstammt der Tradition, Fischtransportfässer durch Verbrennen zu desinfizieren." },
      { title: "Toddy", body: "Historische Getränkekategorie, auch als [[wiki:grog|Grog]] bezeichnet. Warme Mischung aus Spirituose, Wasser, Zucker und Gewürzen." },
      { title: "Tonic Water", body: "Kohlensäurehaltiges Erfrischungsgetränk mit [[wiki:chinin|Chinin]]. Klassischer Mixer für [[wiki:gin-tonic|Gin Tonic]] und [[wiki:vodka-tonic|Vodka Tonic]]." },
      { title: "Topping", body: "Garnierungselement, das oben auf den Drink aufgebracht wird: Sahne, Soda, [[wiki:bitters|Bitters]] oder geriebene [[wiki:muskatnuss|Muskatnuss]]." },
      { title: "Traubenbrand", body: "Brand aus Traubenmaische. Anders als [[wiki:weinbrand|Weinbrand]], der aus Wein destilliert wird." },
      { title: "Trester", body: "Gepresste Rückstände der Weinproduktion: Traubenschalen, Stiele und Kerne. Basis für [[wiki:grappa|Grappa]] und andere Tresterbrand-Spirituosen." },
      { title: "Tresterbrand", body: "Spirituosenkategorie aus Trester (Pressrückständen). Prominente Vertreter: [[wiki:grappa|Grappa]] (Italien), [[wiki:marc|Marc]] (Frankreich), [[wiki:orujo|Orujo]] (Spanien), [[wiki:tsikoudia|Tsikoudia]] und [[wiki:tsipouro|Tsipouro]] (Griechenland)." },
      { title: "Trinkkultur", body: "Jahrtausendealtes, global verbreitetes Kulturphänomen. Alkohol ist in Zeremonien, Feiern, Geschäftstreffen und religiöse Rituale eingebettet." },
      { title: "Triple Sec", body: "\"Dreifach trocken\" – [[wiki:curacao|Curaçao]] mit höherem Alkoholgehalt (über 30 %). Cointreau ist der bekannteste Vertreter. Wichtige Cocktailzutat für [[wiki:margarita|Margarita]], [[wiki:cosmopolitan|Cosmopolitan]] und [[wiki:sidecar|Sidecar]]." },
      { title: "Tsikoudia", body: "Kretischer Tresterbrand, klar und unverfälscht. Vergleichbar mit der italienischen [[wiki:grappa|Grappa]]." },
      { title: "Tsipouro", body: "Griechischer Tresterbrand, entweder pur oder mit Anis aromatisiert. Ähnelt [[wiki:grappa|Grappa]] und [[wiki:tsikoudia|Tsikoudia]]." },
      { title: "Tumbler", body: "Robustes, breites Whiskyglas mit dickem Boden und ohne Stiel. Auch Old Fashioned Glas oder Rocks Glass genannt." },
      { title: "Twist", body: "Technik, bei der Zitrusöle aus einer Schale über dem Drink ausgedrückt und der Glasrand damit bestrichen werden. Die verdrehte Schale dient anschließend als Dekoration." },

      # --- U ---
      { title: "Umeshu", body: "Japanischer Likör aus Ume-Früchten (einer Aprikosensorte), landläufig als \"Pflaumenwein\" bezeichnet. Obwohl Alkoholstärke weinartig, ist es technisch ein Likör." },
      { title: "Untersetzer", body: "Schutzunterlage aus verschiedenen Materialien unter Gläsern. Schützt vor Kondenswasser und Kratzern. Auch [[wiki:coaster|Coaster]] oder [[wiki:filz|Filz]] genannt." },

      # --- V ---
      { title: "Veladora", body: "Kerzenglas aus mexikanischen Kirchen, als 8 cl Mezcal-Trinkgefäß zweckentfremdet. Trägt traditionell ein Kreuz auf dem Boden." },
      { title: "Verjus", body: "Saft unreifer Weintrauben. Herb und säuerlich. Als Säuerungsmittel in der Küche und als Cocktailzutat. Auch [[wiki:agrest|Agrest]] genannt." },
      { title: "Vermouth", body: "Aufgespriteter, mit Kräutern (bes. Wermut) aromatisierter Wein. Fundamental in vielen Klassikern wie [[wiki:martini|Martini]], [[wiki:negroni|Negroni]], [[wiki:manhattan|Manhattan]]. Auch als [[wiki:wermut|Wermut]] (dt.) bezeichnet." },
      { title: "Vermouth di Torino", body: "Geschützte Bezeichnung für italienischen Vermouth aus Turin. Die historische Heimat des [[wiki:vermouth|Vermouth]]." },
      { title: "Vintage", body: "Spirituose oder Wein aus einem bestimmten Erntejahr. Besonders bei Single-Vintage-Bottlings für [[wiki:rum|Rum]], [[wiki:cognac|Cognac]] und Schaumweine relevant." },
      { title: "Virgin", body: "Bezeichnung für alkoholfreie Version eines Cocktails. Beispiel: Virgin Mary (alkoholfreie [[wiki:bloody-mary|Bloody Mary]]). Siehe auch [[wiki:mocktail|Mocktail]]." },
      { title: "Vodka", body: "Neutrale, filtierte Spirituose aus Getreide oder Kartoffeln. In der EU mindestens 37,5 % Alkohol. Charakterlos im Geschmack – ideal als [[wiki:basis|Basis]] für viele Cocktails." },
      { title: "Vollrohrzucker", body: "Unraffinierter Rohrzucker mit hohem Mineralstoff- und Vitamingehalt. Intensives Melassearoma. Stärker im Geschmack als [[wiki:rohrzucker|Rohrzucker]]." },
      { title: "VS", body: "\"Very Special\" – inoffizielle Qualitätsbezeichnung für [[wiki:calvados|Calvados]] und [[wiki:cognac|Cognac]], bei der der jüngste Bestandteil mindestens 2 Jahre gereift ist." },
      { title: "VSOP", body: "\"Very Superior Old Pale\" – Mindestlagerung von 4 Jahren für [[wiki:armagnac|Armagnac]], [[wiki:cognac|Cognac]] und [[wiki:brandy|Brandy]]. Auch für [[wiki:calvados|Calvados]] und martinikanischen [[wiki:rum|Rum]] angewendet." },
      { title: "VVSOP", body: "\"Very Very Superior Old Pale\" – Mindestlagerung von 5 Jahren für [[wiki:armagnac|Armagnac]], [[wiki:cognac|Cognac]] und [[wiki:brandy|Brandy]]." },
      { title: "XO", body: "\"Extra Old\" – inoffizielle Bezeichnung für [[wiki:calvados|Calvados]] und [[wiki:cognac|Cognac]] mit mindestens 6 Jahren Mindestreifezeit. Auch als *Hors d'âge* oder *Napoléon* bezeichnet." },

      # --- W ---
      { title: "Wedges", body: "Fruchtschnitze, besonders von Zitrusfrüchten: vom Stiel zur Blüte in kleine Stücke geschnitten. Klassische Garnierung und Zutat." },
      { title: "Wermut", body: "Artemisia absinthium – aromatische Pflanze, die sowohl in [[wiki:absinth|Absinth]] als auch in [[wiki:vermouth|Vermouth]] verwendet wird. Verleiht bittere, würzige Noten." },
      { title: "Whipped Cream", body: "Geschlagene Sahne. Verwendung als Topping bei Cocktails wie Irish Coffee oder [[wiki:fiaker|Fiaker]]." },
      { title: "Whisky", body: "Getreidebrand mit vielfältiger regionaler Ausprägung. Hauptkategorien: [[wiki:scotch|Scotch]], [[wiki:bourbon|Bourbon]], [[wiki:rye-whiskey|Rye Whiskey]], Irish Whiskey, japanischer Whisky. Mindestens 3 Jahre Fassreifung bei Scotch. Schreibweise \"Whiskey\" für irische und amerikanische Produkte." },
      { title: "Winzersekt", body: "Schaumwein nach der Champagner-Methode ohne geschützte Herkunftsbezeichnung." },

      # --- X ---
      { title: "Xanthan", body: "Natürlich vorkommendes Polysaccharid als Verdickungsmittel in der Lebensmittelindustrie und Molekulargastronomie. Kann zur Texturveränderung von Cocktailzutaten eingesetzt werden." },
      { title: "Xérès", body: "Spanische und französische Bezeichnung für [[wiki:sherry|Sherry]] aus [[wiki:jerez|Jerez]]." },
      { title: "Yuzu", body: "Chinesische Zitrusfrucht, in Japan kultiviert und populär. Erscheinungsbild ähnlich einer Mandarine, Geschmack intensiv sauer und bitter. Verleiht Cocktails exotische Zitrusnoten." },

      # --- Z ---
      { title: "Zapfen", body: "Schweizer Bezeichnung für den Korken einer Flasche." },
      { title: "Zeste", body: "Abgestreiftes Stück Zitrusschale; es wird nur die äußere, aromatische Schicht (ohne weiße Pith) verwendet." },
      { title: "Zestenreißer", body: "Werkzeug zum Schneiden feiner Zestenstreifen aus Zitrusschalen. Auch Fadenschneider oder Channel Knife (engl.) genannt." },
      { title: "Zigarrenbrand", body: "Im Fass gereifte Spirituose, die von Rauchern geschätzt wird, weil der Alkohol weniger aggressiv wirkt. Klassiker: [[wiki:rum|Rum]], [[wiki:whisky|Whisky]], [[wiki:cognac|Cognac]] sowie gereifte Steinobstbrände." },
      { title: "Ziseliermesser", body: "Spezialmesser zum dekorativen Einschnitzen von Früchten und Gemüse für die Garnitur." },
      { title: "Zoom", body: "Seltenes europäisches Heißgetränk aus Spirituose, Sahne und Honig." }
    ]

    force = ENV["FORCE"] == "true"
    created = 0
    updated = 0
    skipped = 0

    source_footer = "\n\n---\n\n*Quelle: [Forum: Lexikon](https://www.cocktailscout.de/cocktailforum/beitrag/AujmVOOB)*"

    entries.each do |entry|
      full_body = entry[:body] + source_footer
      article = WikiArticle.find_or_initialize_by(title: entry[:title])
      if article.new_record?
        article.assign_attributes(body: full_body, user: author, published: true)
        article.save!
        created += 1
      elsif force
        article.update!(body: full_body)
        updated += 1
      else
        skipped += 1
        next
      end
      created += 1
    end

    puts "Lexikon-Seeder abgeschlossen: #{created} erstellt, #{updated} aktualisiert, #{skipped} übersprungen."
  end
end
