// Mirrors BbcodeHelper::SMILEYS from app/helpers/bbcode_helper.rb.
// All expr values must be RegExp with the global flag for replace() to work correctly.
export const SMILEYS = [
  { name: "fröhlich",    filename: "laechel.gif",     shortcut: ":)",           expr: /:-?\)/gi },
  { name: "traurig",     filename: "traurig.gif",      shortcut: ":(",           expr: /:-?\(/gi },
  { name: "zwinker",     filename: "zwinker.gif",      shortcut: ";)",           expr: /;-?\)/gi },
  { name: "cool",        filename: "cool.gif",         shortcut: "8-)",          expr: /8-\)/gi },
  { name: "ätsch",       filename: "aetsch.gif",       shortcut: ":-p",          expr: /:-p/gi },
  { name: "weinend",     filename: "heul.gif",         shortcut: ":cry:",        expr: /:cry:/g },
  { name: "grins",       filename: "grins.gif",        shortcut: ":D",           expr: /:-?D/gi },
  { name: "verwirrt",    filename: "verwirrt.gif",     shortcut: ":-s",          expr: /:-S/gi },
  { name: "überrascht",  filename: "ueberrascht.gif",  shortcut: ":-O",          expr: /:-o/gi },
  { name: "wütend",      filename: "wuetend.gif",      shortcut: ":boese:",      expr: /:boese:/g },
  { name: "unschuldig",  filename: "unschuldig.gif",   shortcut: ":unschuldig:", expr: /:unschuldig:/g },
  { name: "hmm",         filename: "hmm.gif",          shortcut: ":-/",          expr: /:-\//g },
  { name: "schaem",      filename: "schaem.gif",       shortcut: ":schaem:",     expr: /:schaem:/g },
  { name: "ausschenken", filename: "ausschenken.gif",  shortcut: ":ausschenken:", expr: /:ausschenken:/g },
  { name: "hurra",       filename: "hurra.gif",        shortcut: ":hurra:",      expr: /:hurra:/g },
  { name: "lala",        filename: "lala.gif",         shortcut: ":lala:",       expr: /:lala:/g },
  { name: "lol",         filename: "lol.gif",          shortcut: ":lol:",        expr: /:lol:/g },
  { name: "party",       filename: "party.gif",        shortcut: ":party:",      expr: /:party:/g },
  { name: "stösschen",   filename: "stoesschen.gif",   shortcut: ":stoesschen:", expr: /:stoesschen:/g },
  { name: "super",       filename: "super.gif",        shortcut: ":super:",      expr: /:super:/g },
  { name: "tröst",       filename: "troest.gif",       shortcut: ":troest:",     expr: /:troest:/g },
  { name: "vogel",       filename: "vogel.gif",        shortcut: ":vogel:",      expr: /:vogel:/g },
  { name: "wink",        filename: "wink.gif",         shortcut: ":wink:",       expr: /:wink:/g },
  { name: "gelage",      filename: "gelage.gif",       shortcut: ":gelage:",     expr: /:gelage:/g },
  { name: "kater",       filename: "kater.gif",        shortcut: ":kater:",      expr: /:kater:/g },
]
