# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  Exclude:
    - 'legacy/**/*'
    - 'db/legacy/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/TrailingWhitespace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false